### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by nunojesus** [dougolson/Algorithmic-Music#1]
Hi,
I have design this logo for an Algorithm Music project, if you like you can keap it for this project.
If you want it I will give you all the formats of the design free. If you want to make changes please specify.

Greetings

![algo](https://user-images.githubusercontent.com/34600369/39490606-4ddcbbde-4d81-11e8-9972-2315d0e0950a.png)

**Comment by dougolson** [comment]
Hi Nuno - this is cool! I'm going to put up a little readme for the
repository and I'll use one of the logos and credit you I think I like the
one enclosed in a circle with a white background best, but they all look
cool. I want to do more with this project, but it's a pretty challenging
problem. At least for me it is! Having a nice logo should provide a little
extra motivation!

Send me the files for sure - I have all the adobe stuff, so pretty much any
format will work.

Cheers!

Doug

**Comment by nunojesus** [comment]
Ok, I will send you the files tonigh, do you want me to put the name of the project in the logo?

Greetings 
Nuno

**Comment by nunojesus** [comment]
Here are some of the logo variations with text, the font is Montserrate bold, I think it looks great with the logo. 

![algoritmo](https://user-images.githubusercontent.com/34600369/39639042-0534ea32-4fc0-11e8-9992-8985fa9c8301.png)
![algoritmo2](https://user-images.githubusercontent.com/34600369/39639044-05556096-4fc0-11e8-9c0d-cd66723c2720.png)
![algoritmo3](https://user-images.githubusercontent.com/34600369/39639045-05754eec-4fc0-11e8-85fa-b6e04b1c882e.png)
![algoritmo4](https://user-images.githubusercontent.com/34600369/39639047-059c319c-4fc0-11e8-8eb0-e59eb82b0f5c.png)
![algoritmo5](https://user-images.githubusercontent.com/34600369/39639048-05bce900-4fc0-11e8-9a31-c2c10cb372be.png)
