### ISSUE TITLE
License

### ISSUE THREAD

**Issue by nunojesus** [dougolson/Algorithmic-Music#2]
Hello, do you have a license?

**Comment by dougolson** [comment]
Hi Nuno,

Sorry - I've been caught up in work / family stuff. A license? For the code
on github? At present, no - I should probably put something up. Is that
what you mean?

Doug

**Comment by nunojesus** [comment]
Hi Doug, I saw in lots of projects the license file, so I ask you that because I was thinking that you maybe forgot to add a license ti the project. Im contributing since the january and I know that people that want to contribute usually do in projects with license. Greetings

**Comment by dougolson** [comment]
Hi Nuno,

I put the repo under the MIT license. Thanks for the heads up on that good
practice. I should add licenses to my other repos too!

I have lots of ideas for this project - more ideas than time to implement
them...

Cheers!

Doug
